pragma Singleton

import QtQuick
import Quickshell
import Quickshell.Io

// Palette generated by matugen from the current wallpaper (dotfiles/matugen).
// Written to ~/.local/state/matugen/colors.json by `just theme` / `just wallpaper`,
// which is why it lives under runtime state rather than this repo. Falls back to
// a hardcoded dark palette when the file is missing or malformed, so the shell
// works before matugen has ever run (mirrors the pcall() fallback in hyprland.lua).
Singleton {
    id: root

    property color background: "#1a1a1a"
    property color surface: "#2a2a2a"
    property color text: "#eeeeee"
    property color accent: "#33ccff"
    property color border: "#595959"
    property color error: "#f2b8b5"

    FileView {
        path: Quickshell.env("HOME") + "/.local/state/matugen/colors.json"
        watchChanges: true
        onFileChanged: reload()
        onLoaded: {
            try {
                var parsed = JSON.parse(text())
                if (parsed.background) root.background = parsed.background
                if (parsed.surface) root.surface = parsed.surface
                if (parsed.text) root.text = parsed.text
                if (parsed.accent) root.accent = parsed.accent
                if (parsed.border) root.border = parsed.border
                if (parsed.error) root.error = parsed.error
            } catch (e) {
                // Missing/malformed file: keep the hardcoded fallback above.
            }
        }
    }

    function alpha(color, amount) {
        return Qt.rgba(color.r, color.g, color.b, amount)
    }
}
