------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({
    output   = "desc:ASUSTek",
    mode     = "3840x2160@240",
    position = "auto",
    scale    = 2,
    vrr      = 3,
})


---------------------
---- MY PROGRAMS ----
---------------------

-- Start with uwsm
local uwsm_start  = "uwsm app -- "

-- Set programs that you use
local terminal    = "foot"
local browser     = "zen"
local menu        = "foot --title=launcher fsel -d"


-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
--
hl.on("hyprland.start", function ()
  hl.exec_cmd("systemctl --user start hyprpolkitagent")
  hl.exec_cmd(uwsm_start .. terminal)
  hl.exec_cmd(uwsm_start .. "discord")
  -- Random wallpaper for the session, then regenerate the palette from it.
  -- Not a uwsm app: it is a short-lived script, not a session-scoped process.
  hl.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/wallpaper.sh")
end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "18")
hl.env("XCURSOR_THEME", "Bibata-Modern-Classic")
hl.env("HYPRCURSOR_SIZE", "18")
hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Classic")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")
hl.env("DBUS_SESSION_BUS_ADDRESS", "unix:path=/run/user/1000/bus")
hl.env("SSH_AUTH_SOCK", "/run/user/1000/gcr/ssh")


-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Colors generated by matugen from the current wallpaper (wallpaper.sh / `just theme`).
-- Lives in ~/.local/state because the wallpaper is picked at random each session.
-- pcall-guarded because a plain require() of a missing module kills this whole
-- file, and colors.lua only exists once matugen has run at least once.
local ok, colors = pcall(require, os.getenv("HOME") .. "/.local/state/matugen/colors.lua")
if not ok then
    colors = {
        active_border_1 = "rgba(33ccffee)",
        active_border_2 = "rgba(00ff99ee)",
        inactive_border = "rgba(595959aa)",
        shadow          = 0xee1a1a1a,
    }
end

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in  = 2,
        gaps_out = 4,

        border_size = 2,

        col = {
            active_border   = { colors = {colors.active_border_1, colors.active_border_2}, angle = 45 },
            inactive_border = colors.inactive_border,
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "dwindle",
    },

    decoration = {
        rounding       = 4,
        rounding_power = 2,

        -- Change transparency of focused and unfocused windows
        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = colors.shadow,
        },

        blur = {
            enabled   = true,
            size      = 3,
            passes    = 2,
            vibrancy  = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },
})

hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })

hl.curve("easy",           { type = "spring", mass = 1, stiffness = 445.395625, dampening = 39.568411 })

hl.animation({ leaf = "global",        enabled = true,  speed = 1.2,  bezier = "default" })
hl.animation({ leaf = "border",        enabled = true,  speed = 0.96, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true,  speed = 1.12, spring = "easy" })
hl.animation({ leaf = "windowsIn",     enabled = true,  speed = 0.84, spring = "easy",         style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true,  speed = 0.6,  bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true,  speed = 0.7,  bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true,  speed = 0.58, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true,  speed = 0.42, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true,  speed = 0.72, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 0.8,  bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 0.6,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 0.72, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 0.56, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true,  speed = 1.56, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 0.96, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 1.56, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor",    enabled = true,  speed = 2.8,  bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
hl.workspace_rule({ workspace = "w[tv1]s[false]", gaps_out = 0, gaps_in = 0 })
hl.workspace_rule({ workspace = "f[1]s[false]", gaps_out = 0, gaps_in = 0 })
hl.window_rule({ match = { float = false, workspace = "w[tv1]s[false]" }, border_size = 0 })
hl.window_rule({ match = { float = false, workspace = "w[tv1]s[false]" }, rounding = 0 })
hl.window_rule({ match = { float = false, workspace = "f[1]s[false]" }, border_size = 0 })
hl.window_rule({ match = { float = false, workspace = "f[1]s[false]" }, rounding = 0 })

-- Hide cursor
hl.config({
  cursor = {
    inactive_timeout = 2,
    hide_on_key_press = true,
  }
})

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        force_default_wallpaper = 0,
        disable_hyprland_logo   = true,
        mouse_move_enables_dpms = true,
        key_press_enables_dpms = true,
        focus_on_activate = true,
        close_special_on_empty = true,
    },
})


-- unscale XWayland
hl.config({
  xwayland = {
    force_zero_scaling = true
  }
})

-- toolkit-specific scale
hl.env("GDK_SCALE", "1")

---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "ca",
        kb_variant = "multix",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = false,
        },
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more

-- Terminal shenanigans to open in same dir
hl.bind(mainMod .. " + return", function()
  local w = hl.get_active_window()
  if w and w.class == "foot" then
    hl.dispatch(hl.dsp.send_shortcut({ mods = "CTRL SHIFT", key = "n", window = "pid:" .. w.pid }))
  else
    hl.dispatch(hl.dsp.exec_cmd(uwsm_start .. terminal))
  end
end)
hl.bind(mainMod .. " + W", hl.dsp.window.close())
hl.bind(mainMod .. " + Q", hl.dsp.window.kill())
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"))
hl.bind(mainMod .. " + escape", hl.dsp.exec_cmd(uwsm_start .. "foot --title=powermenu ~/.config/hypr/scripts/powermenu.sh"))
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd([[notify-send "$(date '+%A, %B %d | %H:%M')"]]))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd(uwsm_start .. browser))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + space", hl.dsp.exec_cmd(uwsm_start .. menu))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())

-- Screenshots (grim + slurp, satty to annotate)
hl.bind("Print", hl.dsp.exec_cmd('grim -g "$(slurp)" - | wl-copy'))
hl.bind(mainMod .. " + Print", hl.dsp.exec_cmd('grim -g "$(slurp)" - | satty -f - --copy-command wl-copy'))
hl.bind("SHIFT + Print", hl.dsp.exec_cmd('grim - | wl-copy && notify-send "capture effectuée"'))
hl.bind(mainMod .. " + SHIFT + Print", hl.dsp.exec_cmd('grim - | satty -f - --copy-command wl-copy'))

-- Move focus with mainMod + vim bindings
hl.bind(mainMod .. " + h",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + l", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + k",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + j",  hl.dsp.focus({ direction = "down" }))

-- Swap windows with mainMod + vim bindings
hl.bind(mainMod .. " + SHIFT + h",  hl.dsp.window.swap({ direction = "left" }))
hl.bind(mainMod .. " + SHIFT + l", hl.dsp.window.swap({ direction = "right" }))
hl.bind(mainMod .. " + SHIFT + k",    hl.dsp.window.swap({ direction = "up" }))
hl.bind(mainMod .. " + SHIFT + j",  hl.dsp.window.swap({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,             hl.dsp.focus({ workspace = i}))
    hl.bind(mainMod .. " + SHIFT + " .. key,     hl.dsp.window.move({ workspace = i }))
end

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + D",         hl.dsp.workspace.toggle_special("discord"))
hl.bind(mainMod .. " + SHIFT + D", hl.dsp.window.move({ workspace = "special:discord" }))

-- Global keybind: pass CTRL + SHIFT + M (mute) through to Discord
hl.bind("CTRL + SHIFT + M", hl.dsp.pass({ window = "class:^(discord)$" }))

-- Full screen
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Turn off monitor
hl.bind(mainMod .. " + SHIFT + P", function()
                 hl.timer(function()
                   hl.dispatch(hl.dsp.dpms({ action = "disable" }))
                 end, {timeout = 500, type = "oneshot"})
               end)

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"),                  { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"),                  { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- fsel launcher: floating, centered, fixed terminal size
hl.window_rule({
    name  = "fsel-launcher",
    match = { title = "launcher|powermenu" },

    float  = true,
    center = true,
    size   = { 500, 430 },
    dim_around = true,
    confine_pointer = true,
})

-- Firefox Picture-in-Picture: floating, pinned to all workspaces, no border, top-right corner
hl.window_rule({
    name  = "firefox-pip",
    match = { title = "Picture.?in.?[Pp]icture" },

    float             = true,
    pin               = true,
    size              = { 488, 274 },
    keep_aspect_ratio = true,
    border_size       = 0,
    opacity           = "1.0 override 1.0 override",
    move              = { "monitor_w-window_w-96", "32" },
    rounding          = 0,
})

-- Satty screenshot annotator: floating, centered, 70% of the screen
hl.window_rule({
    name  = "satty-annotator",
    match = { class = "^(com\\.gabm\\.satty)$" },

    float  = true,
    center = true,
    size   = { "(monitor_w*0.7)", "(monitor_h*0.7)" },
})

-- Discord shenanigans
hl.window_rule({
    name = "discord-workspace-colored-border",
    match = { initial_class = "discord" },

    border_color = "rgb(5865F2)",
    pseudo = true,
    workspace = "special:discord",
    size = {"(monitor_w*0.95)","(monitor_h*0.95)"},
    no_initial_focus = true,
    dim_around = true,
})
hl.workspace_rule({ workspace = "special:discord", on_created_empty = "discord" })
