-- GENERATED BY MATUGEN -- do not edit, run `just theme`.
-- Required from hyprland.lua (LOOK AND FEEL section).
return {
    active_border_1 = "rgba({{colors.primary.default.hex_stripped}}ee)",
    active_border_2 = "rgba({{colors.tertiary.default.hex_stripped}}ee)",
    inactive_border = "rgba({{colors.outline_variant.default.hex_stripped}}aa)",
    shadow          = 0xee{{colors.surface_container_lowest.default.hex_stripped}},
}
